# Generated by Django 2.1.7 on 2019-03-27 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('buyer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='b_id', to='homepage.User')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='p_id', to='homepage.User')),
            ],
        ),
        migrations.CreateModel(
            name='Mail',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('message_type', models.PositiveSmallIntegerField()),
                ('bid_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller.Bid')),
                ('buyer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buy_id', to='homepage.User')),
                ('vendor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vend_id', to='homepage.User')),
            ],
        ),
    ]
