# Generated by Django 2.1.7 on 2019-04-09 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mail',
            old_name='vendor_id',
            new_name='recv_id',
        ),
        migrations.RenameField(
            model_name='mail',
            old_name='buyer_id',
            new_name='sender_id',
        ),
    ]
