# Generated by Django 2.1.7 on 2019-03-23 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('email_id', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=20)),
                ('phone_number', models.CharField(max_length=10)),
                ('share_email', models.BooleanField(default=True)),
                ('share_phone', models.BooleanField(default=False)),
            ],
        ),
    ]
