# Generated by Django 2.1.7 on 2019-03-27 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=30)),
                ('is_sold', models.BooleanField(default=False)),
                ('description', models.CharField(max_length=300)),
                ('minimum_bid', models.FloatField()),
                ('current_high_bid', models.FloatField()),
                ('image_link', models.CharField(max_length=100)),
                ('vendor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_id', to='homepage.User')),
            ],
        ),
    ]
