# Generated by Django 2.1.7 on 2019-04-03 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.AddField(
            model_name='product',
            name='cat_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
