# Generated by Django 2.1.7 on 2019-04-03 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0002_auto_20190403_1917'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(default=None, max_length=30),
            preserve_default=False,
        ),
    ]
